version: "3"

services:
  nodeosd:
    build:
      context: .
    image: johnnyzhao/eos-dawn-4.0
    command: /usr/local/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 80:8888
      - 9876:9876
    expose:
      - "9876"
    volumes:
      - /data/nodeosd:/opt/eosio/bin/data-dir

  keosd:
    image: johnnyzhao/eos-dawn-4.0
    command: /usr/local/bin/keosd --wallet-dir /opt/eosio/bin/data-dir
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - /data/keosd:/opt/eosio/bin/data-dir
