version: "3"

services:
  nodeosd:
    build:
      context: .
    image: johnnyzhao/eos-dawn3.0-full
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 80:8888
      - 9876:9876
    expose:
      - "9876"
    volumes:
      - nodeosd-data-volume:/opt/eosio/bin/data-dir

  keosd:
    image: johnnyzhao/eos-dawn3.0-full
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir

volumes:
  keosd-data-volume:
  nodeosd-data-volume:
